SELECT CAST((SELECT COUNT(Ey.sid) FROM ENROLLED Ey WHERE Ey.cnum LIKE 'EE%') AS float)/(SELECT COUNT(Cy.cnum) FROM CLASS Cy WHERE Cy.cnum LIKE 'EE%') - 
CAST((SELECT COUNT(Ex.sid) FROM ENROLLED Ex WHERE Ex.cnum LIKE 'CS%') AS float)/(SELECT COUNT(Cx.cnum) FROM CLASS Cx WHERE Cx.cnum LIKE 'CS%');
